# Generated by Django 5.2.1 on 2025-05-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathlesson',
            name='notes_pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='maths.mathlesson'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='maths.quiz'),
        ),
    ]
